Added build proccess for node on alpine image

diff --git a/.github/workflows/npm-cd.yml b/.github/workflows/npm-cd.yml
--- a/.github/workflows/npm-cd.yml
+++ b/.github/workflows/npm-cd.yml
@@ -23,6 +23,7 @@ jobs:
         steps:
           - name: Checkout
             uses: actions/checkout@v4
+
           - name: Start self hosted EC2 runner
             uses: ./.github/workflows/start-self-hosted-runner
             with:
@@ -100,7 +101,7 @@ jobs:
               with:
                   folder_path: "${{ github.workspace }}/node/rust-client/.cargo"
                   named_os: ${{ matrix.build.NAMED_OS }}
-                
+                                  
             - name: Build Node wrapper
               uses: ./.github/workflows/build-node-wrapper
               with:
@@ -151,6 +152,158 @@ jobs:
                   name: ${{ matrix.build.TARGET }}
                   path: ./node/bin
                   if-no-files-found: error
+            
+            - name: Reset repository
+              if: ${{ matrix.build.ARCH == 'arm64' }}
+              shell: bash
+              run: |
+                git reset --hard
+                git clean -xdf
+
+    checkout-self-hosted-runner:
+        if: github.repository_owner == 'aws'
+        needs: start-self-hosted-runner
+        runs-on: [self-hosted, Linux, ARM64]
+        steps:
+          - name: Setup self-hosted runner access
+            run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/glide-for-redis
+          - name: Checkout
+            uses: actions/checkout@v4        
+    
+    publish-musl-binaries:
+        needs: [start-self-hosted-runner, checkout-self-hosted-runner]
+        if: github.repository_owner == 'aws'
+        name: Publish packages to NPM
+        runs-on: ${{ matrix.build.RUNNER }}
+        container:
+            image: node:alpine
+            options: --user root --privileged
+        strategy:
+            fail-fast: false
+            matrix:
+                build:
+                    - {
+                          OS: ubuntu,
+                          NAMED_OS: linux,
+                          ARCH: arm64,
+                          TARGET: aarch64-unknown-linux-musl,
+                          CONTAINER: "2_28",
+                          RUNNER: [self-hosted, Linux, ARM64],
+                      }
+                    - {
+                          OS: ubuntu,
+                          NAMED_OS: linux,
+                          ARCH: x64,
+                          TARGET: x86_64-unknown-linux-musl,
+                          RUNNER: ubuntu-latest,
+                      }
+        steps:
+            - name: Install dependencies
+              run: |
+                apk update
+                apk add bash envsubst git sed
+            
+            - name: Checkout repository for x64
+              if: ${{ matrix.build.ARCH == 'x64' }}
+              uses: actions/checkout@v4
+              with:
+                  submodules: "true"
+                        
+            - name: Checkout repository for ARM64
+              if: ${{ matrix.build.ARCH == 'arm64' }}
+              run: |
+                  git config --global --add safe.directory $GITHUB_WORKSPACE
+                  git clean -xdf
+                  git reset --hard
+                  git submodule sync
+                  git submodule update --init --recursive
+            
+            - name: Set up access
+              if: ${{ matrix.build.ARCH == 'arm64' }}
+              run: |
+                chown -R $(whoami):$(whoami) $GITHUB_WORKSPACE
+                    
+            - name: Set the release version
+              shell: bash
+              run: |
+                  export version=`if ${{ github.event_name == 'pull_request' }}; then echo '255.255.255'; else echo ${GITHUB_REF:11}; fi`
+                  echo "RELEASE_VERSION=${version}" >> $GITHUB_ENV
+            
+            - name: Set the package name
+              shell: bash
+              run: |
+                export pkg_name=`if [ "${{ matrix.build.ARCH }}" == 'x64' ]; then echo "glide-for-redis-linux-musl-x64"; else echo "glide-for-redis-linux-musl-arm64"; fi`
+                echo "PKG_NAME=${pkg_name}" >> $GITHUB_ENV
+                       
+            - name: Update package version in config.toml
+              uses: ./.github/workflows/update-glide-version
+              with:
+                  folder_path: "${{ github.workspace }}/node/rust-client/.cargo"
+                  named_os: ${{ matrix.build.NAMED_OS }}
+                                 
+            - name: Build Node wrapper
+              uses: ./.github/workflows/build-node-wrapper
+              with:
+                  os: ${{ matrix.build.OS }}
+                  named_os: ${{ matrix.build.NAMED_OS }}
+                  arch: ${{ matrix.build.ARCH }}
+                  target: ${{ matrix.build.TARGET }}
+                  npm_scope: ${{ vars.NPM_SCOPE }}
+                  publish: "true"
+                  github-token: ${{ secrets.GITHUB_TOKEN }}
+
+            - name: Setup node
+              working-directory: ./node
+              run: |
+                npm config set registry https://registry.npmjs.org/
+                npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_AUTH_TOKEN }}
+                npm config set scope ${{ vars.NPM_SCOPE }}
+                           
+            - name: Publish to NPM
+              if: github.event_name != 'pull_request'
+              shell: bash
+              working-directory: ./node
+              run: |
+                  set +e
+                  # Redirect only stderr
+                  { npm_publish_err=$(npm publish --access public 2>&1 >&3 3>&-); } 3>&1
+                  if [[ "$npm_publish_err" == *"You cannot publish over the previously published versions"* ]]
+                  then
+                    echo "Skipping publishing, package already published"
+                  elif [[ ! -z "$npm_publish_err" ]]
+                  then
+                    echo "Failed to publish with error: ${npm_publish_err}"
+                    exit 1
+                  fi
+              env:
+                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
+
+            - name: Pack the Node package
+              shell: bash
+              working-directory: ./node
+              run: |
+                  # Remove the "cpu" and "os" fileds so the base package would be able to install it on ubuntu
+                  sed -i '/"\/\/\/cpu": \[/,/]/d' ./package.json && sed -i '/"\/\/\/os": \[/,/]/d' ./package.json
+                  mkdir -p bin
+                  npm pack --pack-destination ./bin
+                  ls ./bin
+              env:
+                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
+              
+            - name: Upload the Node package
+              if: github.event_name != 'pull_request' 
+              uses: actions/upload-artifact@v3
+              with:
+                  name: ${{ matrix.build.TARGET }}
+                  path: ./node/bin
+                  if-no-files-found: error
+                      
+            - name: Reset repository
+              if: ${{ matrix.build.ARCH == 'arm64' }}
+              shell: bash
+              run: |
+                git reset --hard
+                git clean -xdf
 
     publish-base-to-npm:
         if: github.event_name != 'pull_request'
